[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = [
  'npm install --prefix backend --omit=dev',
  'npm install --omit=dev',
  'npm run build'
]

[start]
cmd = 'NODE_ENV=production node backend/src/server.js'
